# Generated by Django 6.0.2 on 2026-03-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('examen', 'Examen'), ('quiz', 'Quiz'), ('taller', 'Taller'), ('proyecto', 'Proyecto'), ('otro', 'Otro'), ('tarea', 'Tarea')], max_length=20)),
                ('materia', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_objetivo', models.DateField()),
                ('horas_estimadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='api.actividad')),
            ],
        ),
    ]
