# Generated by Django 6.0.2 on 2026-03-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtarea',
            old_name='fecha_objetivo',
            new_name='fecha_entrega',
        ),
    ]
