# Generated by Django 6.0.2 on 2026-03-04 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fecha_objetivo_subtarea_fecha_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subtarea',
            name='created_at',
        ),
    ]
