# Generated by Django 6.0.2 on 2026-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='descripcion',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='horas_estimadas',
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='horas_comp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='actividad',
            name='horas_est',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Media', max_length=10),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('Tarea', 'Tarea'), ('Examen', 'Examen'), ('Taller', 'Taller'), ('Proyecto', 'Proyecto'), ('Quiz', 'Quiz')], max_length=20),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
