# Generated by Django 5.1.15 on 2026-03-05 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_actividad_id_alter_subtarea_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['usuario', 'fecha'], name='api_activid_usuario_130e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['usuario', 'estado'], name='api_activid_usuario_2dc6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='subtarea',
            index=models.Index(fields=['actividad', 'fecha_entrega'], name='api_subtare_activid_c607e7_idx'),
        ),
        migrations.AddIndex(
            model_name='subtarea',
            index=models.Index(fields=['fecha_entrega'], name='api_subtare_fecha_e_b86f48_idx'),
        ),
    ]
