# Generated by Django 6.0.2 on 2026-04-23 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='limite_diario_horas',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Límite de horas estimadas por día (1-16 horas)', max_digits=5, validators=[django.core.validators.MinValueValidator(1, message='El límite debe ser al menos 1 hora'), django.core.validators.MaxValueValidator(16, message='El límite no puede exceder 16 horas')]),
        ),
    ]
