# Generated by Django 5.1.15 on 2026-05-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_actividad_estado_alter_actividad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota obtenida en la actividad (0-10)', max_digits=4, null=True),
        ),
    ]
