# Generated by Django 5.1.15 on 2026-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_actividad_nota'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtarea',
            index=models.Index(fields=['fecha_entrega', 'done'], name='api_subtare_fecha_e_19c81d_idx'),
        ),
    ]
